# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url:
date_format: "ordinal"
title: jsonchan
subtitle: ""
description: "陈兴锐的个人博客"
keywords: 陈兴锐, cxrloveuu, jsonchan, cxr,
timezone: Asia/beijin
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: jsonchan
organization:
organization_url:
github_username: cxrloveuu
location: chengdu, China
email: jsonchan1995@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  - href: /
    label: 首页

  - href: /categories/
    label: 分类

  #   -
  #     href: /archives/
  #     label: 归档

  - href: /wiki/
    label: 维基

  - href: /links/
    label: 链接

  - href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
  - jekyll-github-metadata
  - rouge
  #     - jekyll-html-pipeline
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
#     - jekyll-mentions
collections:
  wiki:
    output: true
    permalink: /wiki/:path/

repository:

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
  username: cxrloveuu
# https://imsun.net/posts/gitment-introduction/
gitment:
  owner: jsonchan
  repo: blog-comments
  oauth:
    client_id: d2e1cbbd298958076462
    client_secret: b42a4178e5fd4a7cf63189ef4b1453b05c375709
# https://github.com/gitalk/gitalk#install
gitalk:
  owner: jsonchan
  repo: blog-comments
  clientID: 082c50e98e6f3d942fe6
  clientSecret: 71787159b4df022478ab58f3232cb3f82cd9727e
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus: false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
  # 是否支持全文搜索
  fulltext: false
  # 最多显示多少条搜索结果
  limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
  analytics_id: UA-80669434-1
